### PR TITLE
Update to allow DELETE and PUT methods in Cross Origin Plugin

### PR DESCRIPTION
**Pull request by agoldenberg**
Trying to use PUT or DELETE methods would fail as they are not in the allowed methods array.

Added them in.

### CODE REVIEW

**Comment by jdpanderson** [comment]
Cool, thanks.

In future, can you submit these against the dev branch if it exists?

**Comment by danbruce** [comment]
I don't think this is the right solution. The initial set of 'GET', 'POST', and 'OPTIONS' are present as "sane defaults" since they are the only verbs allowed (see [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests)) for simple (i.e non-preflighted) requests. This PR changes the defaults to be more relaxed and may expose resources that some users are not expecting to be available cross-origin. Instead, I point your attention to line [122](https://github.com/agoldenberg/SnappyRouter/blob/38169e884bc1f1205713153c46b724cd9132ef4d/src/Vectorface/SnappyRouter/Plugin/AccessControl/CrossOriginRequestPlugin.php#L122) which demonstrates how to return allowed custom HTTP verbs using a configuration option instead of rewriting the defaults for everyone.

**Comment by jdpanderson** [comment]
Geez. I really didn't spend the requisite time thinking about that one. Thanks for the tip about config Dan. Will revert.
On May 13, 2016 16:43, Daniel Bruce <notifications@github.com> wrote:I don't think this is the right solution. The initial set of 'GET', 'POST', and 'OPTIONS' are present as "sane defaults" since they are the only verbs allowed (see this) for simple (i.e non-preflighted) requests. This PR changes the defaults to be more relaxed and may expose resources that some users are not expecting to be available cross-origin. Instead, I point your attention to line 122 which demonstrates how to return allowed custom HTTP verbs using a configuration option instead of rewriting the defaults for everyone.

**Comment by jdpanderson** [comment]
Revert commit is here: https://github.com/Vectorface/SnappyRouter/commit/6965542a9d727ed10769ff25afd17e1ffb469218 <https://github.com/Vectorface/SnappyRouter/commit/6965542a9d727ed10769ff25afd17e1ffb469218>

You’re a stand-up guy Dan. It means a lot that you’d spend the time to point that out.

Cheers,

jon

**Comment by danbruce** [comment]
What can I say? I love SnappyRouter. :-)

**Pull request merged**
